name: ci

on: [push, pull_request]

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Install stable rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Install cargo-audit
        run: cargo install cargo-audit

      - name: Build
        run: cargo build --verbose

      - name: Test
        run: cargo test --verbose

      - name: Lint
        run: cargo clippy -- -D warnings

      - name: Audit
        run: cargo audit
